FROM codercom/code-server:4.96.4

USER root
RUN apt-get update \
    && apt-get install -y curl \
    && curl -fsSL https://deb.nodesource.com/setup_22.x | bash - \
    && apt-get install -y nodejs \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

USER coder
EXPOSE 8080

# Clone repo and copy Next.js template
RUN git clone https://github.com/code100x/mobile-magic.git /tmp/bolty-worker \
    && cp -r /tmp/bolty-worker/nextjs-base-app /app \
    && rm -rf /tmp/bolty-worker


WORKDIR /app
# RUN npm install //still update on dependency will rebuild so no benefit of pre-build just larger image size


RUN wget https://github.com/code100x/mobile-magic/raw/refs/heads/main/ext/bolty-listener-0.0.1.vsix \
    && code-server --install-extension bolty-listener-0.0.1.vsix \
    && rm bolty-listener-0.0.1.vsix


RUN mkdir -p /home/coder/.local/share/code-server/User \
    && echo '{"workbench.colorTheme": "Dark+", "workbench.preferredDarkColorTheme": "Dark+"}' > /home/coder/.local/share/code-server/User/settings.json

CMD ["code-server", "--auth", "none", "--bind-addr", "0.0.0.0:8080", "--disable-telemetry", "/app"]
